"""jmc1 clean baseline

Revision ID: 0001_jmc1
Revises: 
Create Date: 2026-07-12 17:50:01.885326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_jmc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('active_path', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_mode', sa.String(length=40), nullable=True),
    sa.Column('imported_from_active', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'storage_path', name='uq_artifact_snapshot_kind_storage_path')
    )
    op.create_index('ix_artifact_snapshots_kind_activated_at', 'artifact_snapshots', ['kind', 'activated_at'], unique=False)
    op.create_index('ix_artifact_snapshots_kind_status', 'artifact_snapshots', ['kind', 'status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('phase', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('desired_state', sa.String(length=12), server_default='run', nullable=False),
    sa.Column('pgq_job_id', sa.BigInteger(), nullable=True),
    sa.Column('dispatch_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('root_id', sa.String(length=32), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('subject_type', sa.String(length=40), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('checkpoint', sa.JSON(), nullable=True),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('resource_request', sa.JSON(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("desired_state IN ('run', 'pause', 'cancel')", name='ck_jobs_desired_state'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('succeeded', 'failed', 'cancelled', 'dead_letter')", name='ck_jobs_outcome'),
    sa.CheckConstraint("phase IN ('planned', 'queued', 'running', 'stopping', 'terminal')", name='ck_jobs_phase'),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('pgq_job_id')
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'scheduled_at', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_jobs_outcome'), 'jobs', ['outcome'], unique=False)
    op.create_index(op.f('ix_jobs_parent_id'), 'jobs', ['parent_id'], unique=False)
    op.create_index('ix_jobs_parent_status', 'jobs', ['parent_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_phase'), 'jobs', ['phase'], unique=False)
    op.create_index('ix_jobs_phase_eligible', 'jobs', ['phase', 'eligible_at', 'priority', 'created_at'], unique=False)
    op.create_index('ix_jobs_purge', 'jobs', ['status', 'finished_at'], unique=False)
    op.create_index(op.f('ix_jobs_root_id'), 'jobs', ['root_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_subject_id'), 'jobs', ['subject_id'], unique=False)
    op.create_index(op.f('ix_jobs_subject_type'), 'jobs', ['subject_type'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('managed_subtitle_assets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cache_path', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('language_tag', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_sdh', sa.Boolean(), nullable=False),
    sa.Column('is_commentary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=True),
    sa.Column('restore_on_replacement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_restored_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_subtitle_assets_content_sha256'), 'managed_subtitle_assets', ['content_sha256'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('movie_file_path', sa.Text(), nullable=True),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('container', sa.String(length=16), nullable=True, comment='Container/extension: matroska, mp4, ...'),
    sa.Column('radarr_id', sa.Integer(), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('quality_cutoff_met', sa.Boolean(), nullable=True, comment='NULL=unknown, True=current file meets Radarr cutoff, False=below cutoff'),
    sa.Column('current_cf_score', sa.Integer(), nullable=True, comment="Raw aggregate custom-format score from Radarr's current movieFile payload"),
    sa.Column('hdr_type_raw', sa.String(length=64), nullable=True, comment='Raw Radarr dynamic-range descriptor; prefers videoDynamicRangeType and falls back to videoDynamicRange'),
    sa.Column('has_hdr', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has HDR, False=missing HDR'),
    sa.Column('has_dv', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has DV, False=missing DV'),
    sa.Column('preferred_audio_languages_json', sa.JSON(), nullable=True),
    sa.Column('preferred_subtitle_languages_json', sa.JSON(), nullable=True),
    sa.Column('director', sa.String(length=500), nullable=True, comment='Director name from TMDB movie credits — used by the text gate to identify director-credit text on posters.'),
    sa.Column('production_companies_json', sa.JSON(), nullable=True, comment="Production company names from TMDB — used by the text gate to identify studio branding text on posters (e.g. 'Marvel Studios')."),
    sa.Column('tagline', sa.Text(), nullable=True, comment='Movie tagline from TMDB — used by the text gate to allow matching promotional text on posters.'),
    sa.Column('text_profile_id', sa.String(length=64), nullable=True, comment='Optional per-movie text-profile override for the OCR text gate.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.Column('poster_user_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True = a human approved this poster (vs an unreviewed AI pick)'),
    sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'),
    sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'),
    sa.Column('poster_local_backup_path', sa.Text(), nullable=True, comment='Local backup copy for restoring deployed poster bytes'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movies_missing_poster', 'movies', ['id'], unique=False, postgresql_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_movies_radarr_id'), 'movies', ['radarr_id'], unique=True)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_table('radarr_custom_formats',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('include_when_renaming', sa.Boolean(), nullable=False),
    sa.Column('specifications_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radarr_quality_profiles',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('cutoff_format_score', sa.Integer(), nullable=True),
    sa.Column('min_format_score', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_contracts',
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('expected_version', sa.String(length=64), nullable=False),
    sa.Column('durability', sa.String(length=16), nullable=True),
    sa.Column('catalog_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verifier_build', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('component')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=True, comment='Primary ID from Sonarr; required by Fanart.tv'),
    sa.Column('tmdb_id', sa.Integer(), nullable=True, comment='Resolved from Sonarr or TMDB /find endpoint'),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('series_path', sa.Text(), nullable=False, comment='Root folder path from Sonarr'),
    sa.Column('sonarr_id', sa.Integer(), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('season_count', sa.Integer(), nullable=False),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('director', sa.String(length=500), nullable=True),
    sa.Column('production_companies_json', sa.JSON(), nullable=True),
    sa.Column('preferred_audio_languages_json', sa.JSON(), nullable=True),
    sa.Column('preferred_subtitle_languages_json', sa.JSON(), nullable=True),
    sa.Column('show_text_profile_id', sa.String(length=64), nullable=True),
    sa.Column('season_text_profile_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.Column('poster_user_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True = a human approved this poster (vs an unreviewed AI pick)'),
    sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'),
    sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'),
    sa.Column('poster_local_backup_path', sa.Text(), nullable=True, comment='Local backup copy for restoring deployed poster bytes'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_series_missing_poster', 'series', ['id'], unique=False, postgresql_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_series_sonarr_id'), 'series', ['sonarr_id'], unique=True)
    op.create_index(op.f('ix_series_tmdb_id'), 'series', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_series_tvdb_id'), 'series', ['tvdb_id'], unique=True)
    op.create_table('sonarr_custom_formats',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('include_when_renaming', sa.Boolean(), nullable=False),
    sa.Column('specifications_json', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonarr_quality_profiles',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('upgrade_allowed', sa.Boolean(), nullable=True),
    sa.Column('cutoff_format_score', sa.Integer(), nullable=True),
    sa.Column('min_format_score', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitle_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('languages_json', sa.JSON(), nullable=True),
    sa.Column('unknown_action', sa.String(length=10), nullable=False),
    sa.Column('protect_forced', sa.Boolean(), nullable=False),
    sa.Column('protect_default', sa.Boolean(), nullable=False),
    sa.Column('protect_last_full_dialogue', sa.Boolean(), nullable=False),
    sa.Column('include_external', sa.Boolean(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('audit_only', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('hardlink_action', sa.String(length=12), nullable=False),
    sa.Column('backup_mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_metrics_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpu', sa.JSON(), nullable=False),
    sa.Column('gpu', sa.JSON(), nullable=True),
    sa.Column('ram', sa.JSON(), nullable=False),
    sa.Column('disk', sa.JSON(), nullable=False),
    sa.Column('net', sa.JSON(), nullable=False),
    sa.Column('active_jobs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_metrics_samples_created_at', 'system_metrics_samples', ['created_at'], unique=False)
    op.create_table('artifact_snapshot_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('contribution_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_snapshot_movies_artifact_id', 'artifact_snapshot_movies', ['artifact_id'], unique=False)
    op.create_index('ix_artifact_snapshot_movies_movie_id', 'artifact_snapshot_movies', ['movie_id'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('episode_file_path', sa.Text(), nullable=True),
    sa.Column('sonarr_episode_id', sa.Integer(), nullable=True),
    sa.Column('has_hdr', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has HDR, False=missing HDR'),
    sa.Column('has_dv', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has DV, False=missing DV'),
    sa.Column('hdr_type_raw', sa.String(length=64), nullable=True, comment='Raw Sonarr dynamic-range descriptor; prefers videoDynamicRangeType and falls back to videoDynamicRange'),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('audio_languages_json', sa.JSON(), nullable=True),
    sa.Column('subtitle_languages_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_series_id'), 'episodes', ['series_id'], unique=False)
    op.create_index(op.f('ix_episodes_sonarr_episode_id'), 'episodes', ['sonarr_episode_id'], unique=True)
    op.create_table('job_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_group_id', sa.Integer(), nullable=True),
    sa.Column('child_pids', sa.JSON(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'number', name='uq_job_attempt_number')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_attempts_worker_id'), 'job_attempts', ['worker_id'], unique=False)
    op.create_table('job_dispatches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('pgq_job_id', sa.BigInteger(), nullable=True),
    sa.Column('entrypoint', sa.String(length=80), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposition', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("disposition IN ('active', 'succeeded', 'failed', 'cancelled', 'stale', 'superseded')", name='ck_job_dispatches_disposition'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key'),
    sa.UniqueConstraint('job_id', 'generation', name='uq_job_dispatch_generation'),
    sa.UniqueConstraint('pgq_job_id')
    )
    op.create_index(op.f('ix_job_dispatches_job_id'), 'job_dispatches', ['job_id'], unique=False)
    op.create_table('managed_subtitle_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.String(length=32), nullable=False),
    sa.Column('owner_type', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['managed_subtitle_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managed_subtitle_bindings_asset_id'), 'managed_subtitle_bindings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_managed_subtitle_bindings_owner_id'), 'managed_subtitle_bindings', ['owner_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_key', sa.String(length=200), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_resolved_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_movie_id'), 'media_files', ['movie_id'], unique=False)
    op.create_index(op.f('ix_media_files_source_key'), 'media_files', ['source_key'], unique=True)
    op.create_table('movie_custom_format_scores',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('custom_format_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['custom_format_id'], ['radarr_custom_formats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'custom_format_id')
    )
    op.create_table('radarr_overlay_profile_preferences',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('meet_target', sa.String(length=32), nullable=True),
    sa.Column('exceed_target', sa.String(length=32), nullable=True),
    sa.Column('excluded_targets', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['radarr_quality_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('radarr_profile_format_items',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('custom_format_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_format_id'], ['radarr_custom_formats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['radarr_quality_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'custom_format_id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True, comment='TMDB season ID for artwork lookup'),
    sa.Column('episode_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('episode_file_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.Column('poster_user_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='True = a human approved this poster (vs an unreviewed AI pick)'),
    sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'),
    sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'),
    sa.Column('poster_local_backup_path', sa.Text(), nullable=True, comment='Local backup copy for restoring deployed poster bytes'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'season_number', name='uq_seasons_series_number')
    )
    op.create_index(op.f('ix_seasons_episode_file_count'), 'seasons', ['episode_file_count'], unique=False)
    op.create_index('ix_seasons_missing_poster', 'seasons', ['id'], unique=False, postgresql_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    op.create_table('sonarr_overlay_profile_preferences',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('meet_target', sa.String(length=32), nullable=True),
    sa.Column('exceed_target', sa.String(length=32), nullable=True),
    sa.Column('excluded_targets', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['sonarr_quality_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('sonarr_profile_format_items',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('custom_format_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_format_id'], ['sonarr_custom_formats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['sonarr_quality_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'custom_format_id')
    )
    op.create_table('subtitle_policy_bindings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['subtitle_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_policy_bindings_policy_id'), 'subtitle_policy_bindings', ['policy_id'], unique=False)
    op.create_table('artwork_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), server_default='movie', nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(media_type = 'movie'  AND movie_id  IS NOT NULL) OR (media_type = 'series' AND series_id IS NOT NULL) OR (media_type = 'season' AND season_id IS NOT NULL)", name='ck_artwork_events_subject'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artwork_events_media_type'), 'artwork_events', ['media_type'], unique=False)
    op.create_index(op.f('ix_artwork_events_movie_id'), 'artwork_events', ['movie_id'], unique=False)
    op.create_index(op.f('ix_artwork_events_season_id'), 'artwork_events', ['season_id'], unique=False)
    op.create_index(op.f('ix_artwork_events_series_id'), 'artwork_events', ['series_id'], unique=False)
    op.create_table('dovi_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), server_default=sa.text("'movie'"), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('dovi_profile', sa.Integer(), nullable=True),
    sa.Column('dovi_level', sa.Integer(), nullable=True),
    sa.Column('el_present', sa.Boolean(), nullable=True),
    sa.Column('el_type', sa.String(length=4), nullable=True),
    sa.Column('bl_signal_compatibility_id', sa.Integer(), nullable=True),
    sa.Column('source_codec', sa.String(length=16), nullable=True),
    sa.Column('rpu_summary_json', sa.Text(), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(media_type = 'movie' AND movie_id IS NOT NULL) OR (media_type = 'episode' AND episode_id IS NOT NULL)", name='ck_dovi_state_subject'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dovi_state_episode_id'), 'dovi_state', ['episode_id'], unique=True)
    op.create_index(op.f('ix_dovi_state_media_type'), 'dovi_state', ['media_type'], unique=False)
    op.create_index(op.f('ix_dovi_state_movie_id'), 'dovi_state', ['movie_id'], unique=True)
    op.create_table('episode_media_files',
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('episode_id', 'media_file_id')
    )
    op.create_index(op.f('ix_episode_media_files_media_file_id'), 'episode_media_files', ['media_file_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_created_at', 'job_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_job_id_id', 'job_events', ['job_id', 'id'], unique=False)
    op.create_table('letterbox_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), server_default=sa.text("'movie'"), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(media_type = 'movie' AND movie_id IS NOT NULL AND episode_id IS NULL) OR (media_type = 'episode' AND episode_id IS NOT NULL AND movie_id IS NULL)", name='ck_letterbox_event_subject'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letterbox_events_episode_id'), 'letterbox_events', ['episode_id'], unique=False)
    op.create_index(op.f('ix_letterbox_events_media_type'), 'letterbox_events', ['media_type'], unique=False)
    op.create_index(op.f('ix_letterbox_events_movie_id'), 'letterbox_events', ['movie_id'], unique=False)
    op.create_table('letterbox_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), server_default=sa.text("'movie'"), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'prefilter_candidate'"), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=True),
    sa.Column('eligible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('ineligible_reason', sa.String(length=120), nullable=True),
    sa.Column('source_width', sa.Integer(), nullable=True),
    sa.Column('source_height', sa.Integer(), nullable=True),
    sa.Column('prefilter_bucket', sa.String(length=24), nullable=True),
    sa.Column('prefilter_reason', sa.String(length=64), nullable=True),
    sa.Column('prefilter_aspect_ratio', sa.Float(), nullable=True),
    sa.Column('last_prefiltered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recommended_crop_top', sa.Integer(), nullable=True),
    sa.Column('recommended_crop_bottom', sa.Integer(), nullable=True),
    sa.Column('aspect_label', sa.String(length=12), nullable=True),
    sa.Column('applied_crop_top', sa.Integer(), nullable=True),
    sa.Column('applied_crop_bottom', sa.Integer(), nullable=True),
    sa.Column('detect_method', sa.String(length=16), nullable=True),
    sa.Column('samples_json', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_crop_top', sa.Integer(), nullable=True),
    sa.Column('original_crop_bottom', sa.Integer(), nullable=True),
    sa.Column('original_aspect_label', sa.String(length=12), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('variable_ar', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('variable_ar_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(media_type = 'movie' AND movie_id IS NOT NULL AND episode_id IS NULL) OR (media_type = 'episode' AND episode_id IS NOT NULL AND movie_id IS NULL)", name='ck_letterbox_state_subject'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_letterbox_state_episode_id'), 'letterbox_state', ['episode_id'], unique=True)
    op.create_index(op.f('ix_letterbox_state_media_type'), 'letterbox_state', ['media_type'], unique=False)
    op.create_index(op.f('ix_letterbox_state_movie_id'), 'letterbox_state', ['movie_id'], unique=True)
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=10), server_default='movie', nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scorer_name', sa.String(length=20), nullable=True),
    sa.Column('counts_json', sa.Text(), nullable=True),
    sa.Column('timings_json', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('batch_id', sa.String(length=32), nullable=True),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('auto_pick_filename', sa.Text(), nullable=True),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.Column('feedback_event_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("(media_type = 'movie'  AND movie_id  IS NOT NULL) OR (media_type = 'series' AND series_id IS NOT NULL) OR (media_type = 'season' AND season_id IS NOT NULL)", name='ck_pipeline_runs_subject'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_runs_batch_id'), 'pipeline_runs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_media_type'), 'pipeline_runs', ['media_type'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_movie_id'), 'pipeline_runs', ['movie_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_season_id'), 'pipeline_runs', ['season_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_series_id'), 'pipeline_runs', ['series_id'], unique=False)
    op.create_table('subtitle_inventories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('file_signature', sa.String(length=128), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('audio_streams_json', sa.JSON(), nullable=True),
    sa.Column('chapters_count', sa.Integer(), nullable=False),
    sa.Column('attachments_count', sa.Integer(), nullable=False),
    sa.Column('coverage_json', sa.JSON(), nullable=True),
    sa.Column('probe_tool_versions_json', sa.JSON(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_inventories_media_file_id'), 'subtitle_inventories', ['media_file_id'], unique=True)
    op.create_table('subtitle_tracks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('stream_index', sa.Integer(), nullable=True),
    sa.Column('tool_track_id', sa.Integer(), nullable=True),
    sa.Column('external_path', sa.Text(), nullable=True),
    sa.Column('paired_path', sa.Text(), nullable=True),
    sa.Column('codec', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('language_raw', sa.String(length=40), nullable=True),
    sa.Column('language_tag', sa.String(length=40), nullable=False),
    sa.Column('language_source', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_forced', sa.Boolean(), nullable=False),
    sa.Column('is_sdh', sa.Boolean(), nullable=False),
    sa.Column('is_commentary', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['subtitle_inventories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitle_tracks_inventory_id'), 'subtitle_tracks', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitle_tracks_inventory_id'), table_name='subtitle_tracks')
    op.drop_table('subtitle_tracks')
    op.drop_index(op.f('ix_subtitle_inventories_media_file_id'), table_name='subtitle_inventories')
    op.drop_table('subtitle_inventories')
    op.drop_index(op.f('ix_pipeline_runs_series_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_season_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_movie_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_media_type'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_batch_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_letterbox_state_movie_id'), table_name='letterbox_state')
    op.drop_index(op.f('ix_letterbox_state_media_type'), table_name='letterbox_state')
    op.drop_index(op.f('ix_letterbox_state_episode_id'), table_name='letterbox_state')
    op.drop_table('letterbox_state')
    op.drop_index(op.f('ix_letterbox_events_movie_id'), table_name='letterbox_events')
    op.drop_index(op.f('ix_letterbox_events_media_type'), table_name='letterbox_events')
    op.drop_index(op.f('ix_letterbox_events_episode_id'), table_name='letterbox_events')
    op.drop_table('letterbox_events')
    op.drop_index('ix_job_events_job_id_id', table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index('ix_job_events_created_at', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_episode_media_files_media_file_id'), table_name='episode_media_files')
    op.drop_table('episode_media_files')
    op.drop_index(op.f('ix_dovi_state_movie_id'), table_name='dovi_state')
    op.drop_index(op.f('ix_dovi_state_media_type'), table_name='dovi_state')
    op.drop_index(op.f('ix_dovi_state_episode_id'), table_name='dovi_state')
    op.drop_table('dovi_state')
    op.drop_index(op.f('ix_artwork_events_series_id'), table_name='artwork_events')
    op.drop_index(op.f('ix_artwork_events_season_id'), table_name='artwork_events')
    op.drop_index(op.f('ix_artwork_events_movie_id'), table_name='artwork_events')
    op.drop_index(op.f('ix_artwork_events_media_type'), table_name='artwork_events')
    op.drop_table('artwork_events')
    op.drop_index(op.f('ix_subtitle_policy_bindings_policy_id'), table_name='subtitle_policy_bindings')
    op.drop_table('subtitle_policy_bindings')
    op.drop_table('sonarr_profile_format_items')
    op.drop_table('sonarr_overlay_profile_preferences')
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.drop_index('ix_seasons_missing_poster', table_name='seasons', postgresql_where=sa.text('poster_path IS NULL'))
    op.drop_index(op.f('ix_seasons_episode_file_count'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('radarr_profile_format_items')
    op.drop_table('radarr_overlay_profile_preferences')
    op.drop_table('movie_custom_format_scores')
    op.drop_index(op.f('ix_media_files_source_key'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_movie_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_managed_subtitle_bindings_owner_id'), table_name='managed_subtitle_bindings')
    op.drop_index(op.f('ix_managed_subtitle_bindings_asset_id'), table_name='managed_subtitle_bindings')
    op.drop_table('managed_subtitle_bindings')
    op.drop_index(op.f('ix_job_dispatches_job_id'), table_name='job_dispatches')
    op.drop_table('job_dispatches')
    op.drop_index(op.f('ix_job_attempts_worker_id'), table_name='job_attempts')
    op.drop_index(op.f('ix_job_attempts_job_id'), table_name='job_attempts')
    op.drop_table('job_attempts')
    op.drop_index(op.f('ix_episodes_sonarr_episode_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_series_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index('ix_artifact_snapshot_movies_movie_id', table_name='artifact_snapshot_movies')
    op.drop_index('ix_artifact_snapshot_movies_artifact_id', table_name='artifact_snapshot_movies')
    op.drop_table('artifact_snapshot_movies')
    op.drop_index('ix_system_metrics_samples_created_at', table_name='system_metrics_samples')
    op.drop_table('system_metrics_samples')
    op.drop_table('subtitle_policies')
    op.drop_table('sonarr_quality_profiles')
    op.drop_table('sonarr_custom_formats')
    op.drop_index(op.f('ix_series_tvdb_id'), table_name='series')
    op.drop_index(op.f('ix_series_tmdb_id'), table_name='series')
    op.drop_index(op.f('ix_series_sonarr_id'), table_name='series')
    op.drop_index('ix_series_missing_poster', table_name='series', postgresql_where=sa.text('poster_path IS NULL'))
    op.drop_table('series')
    op.drop_table('schema_contracts')
    op.drop_table('radarr_quality_profiles')
    op.drop_table('radarr_custom_formats')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_radarr_id'), table_name='movies')
    op.drop_index('ix_movies_missing_poster', table_name='movies', postgresql_where=sa.text('poster_path IS NULL'))
    op.drop_table('movies')
    op.drop_index(op.f('ix_managed_subtitle_assets_content_sha256'), table_name='managed_subtitle_assets')
    op.drop_table('managed_subtitle_assets')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_subject_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_subject_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_root_id'), table_name='jobs')
    op.drop_index('ix_jobs_purge', table_name='jobs')
    op.drop_index('ix_jobs_phase_eligible', table_name='jobs')
    op.drop_index(op.f('ix_jobs_phase'), table_name='jobs')
    op.drop_index('ix_jobs_parent_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_parent_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_outcome'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_correlation_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_artifact_snapshots_kind_status', table_name='artifact_snapshots')
    op.drop_index('ix_artifact_snapshots_kind_activated_at', table_name='artifact_snapshots')
    op.drop_table('artifact_snapshots')
    # ### end Alembic commands ###
