"""canonical model and configuration

Revision ID: 0002_jmc2a
Revises: 0001_jmc1
Create Date: 2026-07-12 22:07:19.395158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_jmc2a'
down_revision: Union[str, None] = '0001_jmc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # JMC2A is a pre-release cutover with no compatibility or backfill path.
    # Recreate the JMC1 platform tables so no transitional column or constraint
    # survives into the canonical schema.
    op.drop_table("job_events")
    op.drop_table("job_dispatches")
    op.drop_table("job_attempts")
    op.drop_table("jobs")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_revisions",
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("actor", sa.JSON(), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "configuration_current",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("current_version", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("singleton_id = 1", name="ck_configuration_current_singleton"),
        sa.ForeignKeyConstraint(
            ["current_version"],
            ["configuration_revisions.version"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("singleton_id"),
        sa.UniqueConstraint("current_version"),
    )
    op.execute(
        "INSERT INTO configuration_revisions "
        "(version, values, checksum, schema_version, actor, trigger) VALUES "
        "(1, '{}'::json, "
        "'44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a', "
        "1, '{\"kind\":\"system\",\"id\":\"migration\"}'::json, 'migration_seed')"
    )
    op.execute(
        "INSERT INTO configuration_current (singleton_id, current_version) VALUES (1, 1)"
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('payload_version', sa.Integer(), nullable=False),
    sa.Column('result_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('error_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('phase', sa.String(length=16), server_default='planned', nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('desired_state', sa.String(length=12), server_default='run', nullable=False),
    sa.Column('fence_token', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('current_attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('pgq_job_id', sa.BigInteger(), nullable=True),
    sa.Column('dispatch_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('retry_policy', sa.JSON(), nullable=True),
    sa.Column('execution_policy_id', sa.String(length=80), nullable=True),
    sa.Column('configuration_version', sa.BigInteger(), nullable=True),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('root_id', sa.String(length=32), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('retry_of_job_id', sa.String(length=32), nullable=True),
    sa.Column('trigger_kind', sa.String(length=24), server_default='system', nullable=False),
    sa.Column('initiator', sa.JSON(), nullable=True),
    sa.Column('feature_area', sa.String(length=40), server_default='system', nullable=False),
    sa.Column('presentation_family', sa.String(length=40), nullable=True),
    sa.Column('subject_kind', sa.String(length=40), server_default='system', nullable=False),
    sa.Column('subject_reference', sa.String(length=64), nullable=True),
    sa.Column('subject_snapshot', sa.JSON(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('progress_sequence', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('progress_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('current_subject', sa.JSON(), nullable=True),
    sa.Column('attention', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(phase = 'terminal' AND outcome IS NOT NULL AND terminal_at IS NOT NULL) OR (phase <> 'terminal' AND outcome IS NULL AND terminal_at IS NULL)", name='ck_jobs_terminal_consistency'),
    sa.CheckConstraint("desired_state IN ('run', 'pause', 'cancel')", name='ck_jobs_desired_state'),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('succeeded', 'partially_succeeded', 'no_change', 'failed', 'cancelled', 'superseded', 'dead_letter', 'unsafe')", name='ck_jobs_outcome'),
    sa.CheckConstraint("phase IN ('planned', 'queued', 'running', 'stopping', 'terminal')", name='ck_jobs_phase'),
    sa.CheckConstraint("trigger_kind IN ('manual', 'schedule', 'policy', 'batch', 'parent', 'healing', 'system', 'webhook')", name='ck_jobs_trigger_kind'),
    sa.CheckConstraint('dispatch_generation >= 0', name='ck_jobs_dispatch_generation'),
    sa.CheckConstraint('fence_token >= 0', name='ck_jobs_fence_token'),
    sa.CheckConstraint('progress_sequence >= 0', name='ck_jobs_progress_sequence'),
    sa.ForeignKeyConstraint(['current_attempt_id'], ['job_attempts.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['configuration_version'], ['configuration_revisions.version'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retry_of_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    sa.UniqueConstraint('pgq_job_id')
    )
    op.create_index(op.f('ix_jobs_correlation_id'), 'jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_jobs_outcome'), 'jobs', ['outcome'], unique=False)
    op.create_index(op.f('ix_jobs_parent_id'), 'jobs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_jobs_phase'), 'jobs', ['phase'], unique=False)
    op.create_index('ix_jobs_phase_eligible', 'jobs', ['phase', 'eligible_at', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_root_id'), 'jobs', ['root_id'], unique=False)
    op.create_index('ix_jobs_subject', 'jobs', ['subject_kind', 'subject_reference'], unique=False)
    op.create_index(op.f('ix_jobs_subject_reference'), 'jobs', ['subject_reference'], unique=False)
    op.create_index('ix_jobs_terminal_history', 'jobs', ['phase', 'terminal_at'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('job_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('fence_token', sa.BigInteger(), nullable=False),
    sa.Column('pgq_job_id', sa.BigInteger(), nullable=True),
    sa.Column('transport_attempt', sa.Integer(), nullable=True),
    sa.Column('worker_node_id', sa.String(length=100), nullable=True),
    sa.Column('worker_build', sa.String(length=64), nullable=True),
    sa.Column('phase', sa.String(length=16), server_default='admitted', nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=True),
    sa.Column('failure_class', sa.String(length=40), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopping_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_group_id', sa.Integer(), nullable=True),
    sa.Column('cgroup_path', sa.String(length=200), nullable=True),
    sa.Column('host_boot_id', sa.String(length=64), nullable=True),
    sa.Column('process_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('exit_signal', sa.Integer(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('succeeded', 'failed', 'cancelled', 'interrupted', 'retrying')", name='ck_job_attempts_outcome'),
    sa.CheckConstraint("phase IN ('admitted', 'running', 'stopping', 'finished')", name='ck_job_attempts_phase'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'fence_token', name='uq_job_attempt_fence'),
    sa.UniqueConstraint('job_id', 'number', name='uq_job_attempt_number')
    )
    op.create_index(op.f('ix_job_attempts_job_id'), 'job_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_attempts_worker_node_id'), 'job_attempts', ['worker_node_id'], unique=False)
    op.create_foreign_key(
        "fk_jobs_current_attempt_id_job_attempts",
        "jobs",
        "job_attempts",
        ["current_attempt_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_table('job_dispatches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('pgq_job_id', sa.BigInteger(), nullable=True),
    sa.Column('entrypoint', sa.String(length=80), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('eligible_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disposition', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('picked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("disposition IN ('active', 'succeeded', 'failed', 'cancelled', 'stale', 'superseded', 'dead_lettered')", name='ck_job_dispatches_disposition'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key'),
    sa.UniqueConstraint('job_id', 'generation', name='uq_job_dispatch_generation'),
    sa.UniqueConstraint('pgq_job_id')
    )
    op.create_index(op.f('ix_job_dispatches_job_id'), 'job_dispatches', ['job_id'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('event_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_events_created_at', 'job_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index('ix_job_events_job_id_id', 'job_events', ['job_id', 'id'], unique=False)
    op.create_table('worker_nodes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('build', sa.String(length=64), nullable=True),
    sa.Column('boot_id', sa.String(length=64), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('readiness', sa.String(length=16), server_default='starting', nullable=False),
    sa.Column('drain_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('telemetry', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("readiness IN ('starting', 'ready', 'not_ready', 'stopped')", name='ck_worker_nodes_readiness'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_nodes_last_seen_at'), 'worker_nodes', ['last_seen_at'], unique=False)
    op.create_table('job_artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='available', nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('virtual_source', sa.JSON(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('retention_class', sa.String(length=24), server_default='standard', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'available', 'failed', 'expired')", name='ck_job_artifacts_status'),
    sa.CheckConstraint("storage_key IS NULL OR (storage_key NOT LIKE '/%%' AND storage_key NOT LIKE '%%..%%')", name='ck_job_artifacts_confined_storage_key'),
    sa.CheckConstraint('(storage_key IS NOT NULL) <> (virtual_source IS NOT NULL)', name='ck_job_artifacts_one_source'),
    sa.CheckConstraint('size_bytes IS NULL OR size_bytes >= 0', name='ck_job_artifacts_size'),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_artifacts_attempt_id'), 'job_artifacts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_job_artifacts_job_id'), 'job_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_artifacts_kind'), 'job_artifacts', ['kind'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=12), server_default='text', nullable=False),
    sa.Column('encoding', sa.String(length=20), server_default='utf-8', nullable=False),
    sa.Column('compression', sa.String(length=12), server_default='none', nullable=False),
    sa.Column('byte_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('line_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('redacted', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('truncated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_class', sa.String(length=24), server_default='standard', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("compression IN ('none', 'gzip', 'zstd')", name='ck_job_logs_compression'),
    sa.CheckConstraint("format IN ('text', 'jsonl')", name='ck_job_logs_format'),
    sa.CheckConstraint("storage_key NOT LIKE '/%%' AND storage_key NOT LIKE '%%..%%'", name='ck_job_logs_confined_storage_key'),
    sa.CheckConstraint('byte_count >= 0', name='ck_job_logs_byte_count'),
    sa.CheckConstraint('line_count >= 0', name='ck_job_logs_line_count'),
    sa.CheckConstraint('segment >= 0', name='ck_job_logs_segment'),
    sa.ForeignKeyConstraint(['attempt_id'], ['job_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'segment', name='uq_job_log_attempt_segment')
    )
    op.create_index(op.f('ix_job_logs_attempt_id'), 'job_logs', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_table('media_operation_details',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('operation_kind', sa.String(length=60), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=True),
    sa.Column('media_snapshot', sa.JSON(), nullable=False),
    sa.Column('target_snapshot', sa.JSON(), nullable=False),
    sa.Column('input_signature', sa.String(length=160), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation', sa.JSON(), nullable=True),
    sa.Column('requested_target', sa.JSON(), nullable=True),
    sa.Column('expected_target', sa.JSON(), nullable=True),
    sa.Column('actual_target', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('atomicity', sa.JSON(), nullable=True),
    sa.Column('backup', sa.JSON(), nullable=True),
    sa.Column('publish', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_media_operation_details_media_file_id'), 'media_operation_details', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_media_operation_details_operation_kind'), 'media_operation_details', ['operation_kind'], unique=False)
    op.add_column('artwork_events', sa.Column('subject_snapshot', sa.JSON(), server_default='{}', nullable=False))
    op.drop_constraint('ck_artwork_events_subject', 'artwork_events', type_='check')
    op.create_check_constraint(
        'ck_artwork_events_subject',
        'artwork_events',
        "(media_type = 'movie' AND movie_id IS NOT NULL) OR "
        "(media_type = 'series' AND series_id IS NOT NULL) OR "
        "(media_type = 'season' AND season_id IS NOT NULL) OR "
        "(movie_id IS NULL AND series_id IS NULL AND season_id IS NULL)",
    )
    op.drop_constraint(op.f('artwork_events_movie_id_fkey'), 'artwork_events', type_='foreignkey')
    op.drop_constraint(op.f('artwork_events_season_id_fkey'), 'artwork_events', type_='foreignkey')
    op.drop_constraint(op.f('artwork_events_series_id_fkey'), 'artwork_events', type_='foreignkey')
    op.create_foreign_key(None, 'artwork_events', 'movies', ['movie_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'artwork_events', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'artwork_events', 'seasons', ['season_id'], ['id'], ondelete='SET NULL')
    op.add_column('episodes', sa.Column('is_present', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('episodes', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('episodes', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_episodes_is_present'), 'episodes', ['is_present'], unique=False)
    op.add_column('letterbox_events', sa.Column('subject_snapshot', sa.JSON(), server_default='{}', nullable=False))
    op.drop_constraint('ck_letterbox_event_subject', 'letterbox_events', type_='check')
    op.create_check_constraint(
        'ck_letterbox_event_subject',
        'letterbox_events',
        "(media_type = 'movie' AND movie_id IS NOT NULL AND episode_id IS NULL) OR "
        "(media_type = 'episode' AND episode_id IS NOT NULL AND movie_id IS NULL) OR "
        "(movie_id IS NULL AND episode_id IS NULL)",
    )
    op.drop_constraint(op.f('letterbox_events_movie_id_fkey'), 'letterbox_events', type_='foreignkey')
    op.drop_constraint(op.f('letterbox_events_episode_id_fkey'), 'letterbox_events', type_='foreignkey')
    op.create_foreign_key(None, 'letterbox_events', 'episodes', ['episode_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'letterbox_events', 'movies', ['movie_id'], ['id'], ondelete='SET NULL')
    op.add_column('media_files', sa.Column('is_present', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('media_files', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_media_files_is_present'), 'media_files', ['is_present'], unique=False)
    op.add_column('movies', sa.Column('is_present', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('movies', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('movies', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_movies_is_present'), 'movies', ['is_present'], unique=False)
    op.add_column('pipeline_runs', sa.Column('subject_snapshot', sa.JSON(), server_default='{}', nullable=False))
    op.drop_constraint('ck_pipeline_runs_subject', 'pipeline_runs', type_='check')
    op.create_check_constraint(
        'ck_pipeline_runs_subject',
        'pipeline_runs',
        "(media_type = 'movie' AND movie_id IS NOT NULL) OR "
        "(media_type = 'series' AND series_id IS NOT NULL) OR "
        "(media_type = 'season' AND season_id IS NOT NULL) OR "
        "(movie_id IS NULL AND series_id IS NULL AND season_id IS NULL)",
    )
    op.drop_constraint(op.f('pipeline_runs_movie_id_fkey'), 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(op.f('pipeline_runs_season_id_fkey'), 'pipeline_runs', type_='foreignkey')
    op.drop_constraint(op.f('pipeline_runs_series_id_fkey'), 'pipeline_runs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_runs', 'seasons', ['season_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pipeline_runs', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pipeline_runs', 'movies', ['movie_id'], ['id'], ondelete='SET NULL')
    op.add_column('seasons', sa.Column('is_present', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('seasons', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('seasons', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_seasons_is_present'), 'seasons', ['is_present'], unique=False)
    op.add_column('series', sa.Column('is_present', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('series', sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('series', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_series_is_present'), 'series', ['is_present'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("0002_jmc2a is an irreversible pre-release canonical cutover")
    # ### end Alembic commands ###
