"""add genres, pipeline_runs, artwork_events, artwork deploy columns

Revision ID: 14e34b6bd956
Revises: 730ffe1dcfc3
Create Date: 2026-06-12 19:13:29.861522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e34b6bd956'
down_revision: Union[str, None] = '730ffe1dcfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artwork_events_movie_id'), 'artwork_events', ['movie_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scorer_name', sa.String(length=20), nullable=True),
    sa.Column('counts_json', sa.Text(), nullable=True),
    sa.Column('archive_path', sa.Text(), nullable=True),
    sa.Column('output_dir', sa.Text(), nullable=True),
    sa.Column('feedback_event_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_pipeline_runs_movie_id'), 'pipeline_runs', ['movie_id'], unique=False)
    op.add_column('movies', sa.Column('genres', sa.JSON(), nullable=True))
    op.add_column('movies', sa.Column('poster_user_approved', sa.Boolean(), nullable=False, server_default=sa.false(), comment='True = a human approved this poster (vs an unreviewed AI pick)'))
    op.add_column('movies', sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'))
    op.add_column('movies', sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'))
    op.add_column('seasons', sa.Column('poster_user_approved', sa.Boolean(), nullable=False, server_default=sa.false(), comment='True = a human approved this poster (vs an unreviewed AI pick)'))
    op.add_column('seasons', sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'))
    op.add_column('seasons', sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'))
    op.add_column('series', sa.Column('poster_user_approved', sa.Boolean(), nullable=False, server_default=sa.false(), comment='True = a human approved this poster (vs an unreviewed AI pick)'))
    op.add_column('series', sa.Column('poster_deployed_filename', sa.String(length=255), nullable=True, comment='Filename written into the media folder (e.g. poster.jpg) — restoration re-uses this exact name'))
    op.add_column('series', sa.Column('poster_deployed_at', sa.DateTime(timezone=True), nullable=True, comment='When the poster was last deployed to the media folder'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'poster_deployed_at')
    op.drop_column('series', 'poster_deployed_filename')
    op.drop_column('series', 'poster_user_approved')
    op.drop_column('seasons', 'poster_deployed_at')
    op.drop_column('seasons', 'poster_deployed_filename')
    op.drop_column('seasons', 'poster_user_approved')
    op.drop_column('movies', 'poster_deployed_at')
    op.drop_column('movies', 'poster_deployed_filename')
    op.drop_column('movies', 'poster_user_approved')
    op.drop_column('movies', 'genres')
    op.drop_index(op.f('ix_pipeline_runs_movie_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_artwork_events_movie_id'), table_name='artwork_events')
    op.drop_table('artwork_events')
    # ### end Alembic commands ###
