"""baseline current schema

Revision ID: 730ffe1dcfc3
Revises: 
Create Date: 2026-06-12 19:12:12.891976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730ffe1dcfc3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('movie_file_path', sa.Text(), nullable=True),
    sa.Column('radarr_id', sa.Integer(), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('has_hdr', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has HDR, False=missing HDR'),
    sa.Column('has_dv', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has DV, False=missing DV'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movies_missing_poster', 'movies', ['id'], unique=False, sqlite_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_movies_radarr_id'), 'movies', ['radarr_id'], unique=True)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tvdb_id', sa.Integer(), nullable=True, comment='Primary ID from Sonarr; required by Fanart.tv'),
    sa.Column('tmdb_id', sa.Integer(), nullable=True, comment='Resolved from Sonarr or TMDB /find endpoint'),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('series_path', sa.Text(), nullable=False, comment='Root folder path from Sonarr'),
    sa.Column('sonarr_id', sa.Integer(), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('season_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_series_missing_poster', 'series', ['id'], unique=False, sqlite_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_series_sonarr_id'), 'series', ['sonarr_id'], unique=True)
    op.create_index(op.f('ix_series_tmdb_id'), 'series', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_series_tvdb_id'), 'series', ['tvdb_id'], unique=True)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('episode_file_path', sa.Text(), nullable=True),
    sa.Column('sonarr_episode_id', sa.Integer(), nullable=True),
    sa.Column('has_hdr', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has HDR, False=missing HDR'),
    sa.Column('has_dv', sa.Boolean(), nullable=True, comment='NULL=not checked, True=has DV, False=missing DV'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_series_id'), 'episodes', ['series_id'], unique=False)
    op.create_index(op.f('ix_episodes_sonarr_episode_id'), 'episodes', ['sonarr_episode_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True, comment='TMDB season ID for artwork lookup'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('poster_path', sa.Text(), nullable=True, comment='Deployed poster file path. NULL = needs poster.'),
    sa.Column('poster_source', sa.String(length=20), nullable=True, comment='Source database: tmdb, fanart, tvdb, tvmaze'),
    sa.Column('poster_source_url', sa.Text(), nullable=True, comment='Original remote URL for reference'),
    sa.Column('poster_ai_selected', sa.Boolean(), nullable=False, comment='Was this poster chosen by the AI engine?'),
    sa.Column('poster_embedding', sa.LargeBinary(), nullable=True, comment='Serialised numpy CLIP embedding of the deployed poster'),
    sa.Column('poster_sha256', sa.String(length=64), nullable=True, comment='SHA-256 hash of the deployed poster file'),
    sa.Column('poster_phash', sa.String(length=16), nullable=True, comment='Perceptual hash of the deployed poster'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'season_number', name='uq_seasons_series_number')
    )
    op.create_index('ix_seasons_missing_poster', 'seasons', ['id'], unique=False, sqlite_where=sa.text('poster_path IS NULL'))
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.drop_index('ix_seasons_missing_poster', table_name='seasons', sqlite_where=sa.text('poster_path IS NULL'))
    op.drop_table('seasons')
    op.drop_index(op.f('ix_episodes_sonarr_episode_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_series_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_series_tvdb_id'), table_name='series')
    op.drop_index(op.f('ix_series_tmdb_id'), table_name='series')
    op.drop_index(op.f('ix_series_sonarr_id'), table_name='series')
    op.drop_index('ix_series_missing_poster', table_name='series', sqlite_where=sa.text('poster_path IS NULL'))
    op.drop_table('series')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_radarr_id'), table_name='movies')
    op.drop_index('ix_movies_missing_poster', table_name='movies', sqlite_where=sa.text('poster_path IS NULL'))
    op.drop_table('movies')
    # ### end Alembic commands ###
